const $ = id => document.getElementById(id); let latest;
const percent = value => value == null ? "Unavailable" : `${Math.round(value * 100)}%`;
const fact = (label, value) => `<div><span>${label}</span><strong>${value ?? "Unknown"}</strong></div>`;
function setLoading(active) { $("loading").hidden = !active; $("hero").hidden = active; }
function render(data) {
  latest = data; $("results").hidden = false; $("domain").textContent = data.domain; $("risk").textContent = `${data.risk_level} RISK`; $("risk").className = `risk ${data.risk_level.toLowerCase()}`; $("probability").textContent = percent(data.phishing_probability); $("target").textContent = data.target_brand || "No strong match detected"; $("targetDomain").textContent = data.target_domain || "Limited reference database";
  const f = data.features; $("similarities").innerHTML = [["DOMAIN SIMILARITY", percent(f.brand_similarity)], ["HTML SIMILARITY", percent(f.html_similarity)], ["VISUAL SIMILARITY", percent(f.visual_similarity)]].map(([a,b]) => `<article class="metric"><p>${a}</p><strong>${b}</strong></article>`).join("");
  $("domainFacts").innerHTML = fact("TLD", f.tld ? `.${f.tld}` : "Unknown") + fact("DOMAIN AGE", f.domain_age_days == null ? null : `${f.domain_age_days} days`) + fact("DIGITS", f.digit_count) + fact("HYPHENS", f.hyphen_count) + fact("SUBDOMAINS", f.subdomain_count) + fact("HTTPS", f.has_https ? "Yes" : "No");
  $("pageFacts").innerHTML = fact("FORMS", f.form_count) + fact("INPUTS", f.input_count) + fact("PASSWORD FIELDS", f.password_field_count) + fact("IMAGES", f.image_count) + fact("SCRIPTS", f.script_count) + fact("IFRAMES", f.iframe_count);
  $("reasons").innerHTML = data.reasons.map(x => `<li>${x}</li>`).join(""); $("pipeline").innerHTML = Object.entries(data.pipeline).map(([key, state]) => `<div><span>${key.replaceAll("_", " ")}</span><b class="${state}">${state === "complete" ? "✓" : "—"} ${state}</b></div>`).join("");
  const shots = data.screenshots; $("comparison").hidden = !(shots.reference && shots.submitted); if (!$("comparison").hidden) { $("referenceShot").src = shots.reference; $("submittedShot").src = shots.submitted; }
  $("error").textContent = data.warnings.join(" ");
}
$("scanForm").addEventListener("submit", async event => { event.preventDefault(); $("results").hidden = true; $("error").textContent = ""; setLoading(true); const lines = [["Analyzing domain…", "Extracting safe URL characteristics."], ["Finding possible legitimate matches…", "Comparing the domain with local reference data."], ["Inspecting webpage…", "Retrieving passive HTML signals, if available."], ["Running ML model…", "Generating a measured risk estimate."]]; let i=0; const timer=setInterval(()=>{i=(i+1)%lines.length; $("loadingText").textContent=lines[i][0]; $("loadingDetail").textContent=lines[i][1]},800); try { const response=await fetch("/analyze", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:$("urlInput").value})}); const body=await response.json(); if(!response.ok) throw new Error(body.detail || "The analysis service is unavailable."); render(body); } catch(error) { $("error").textContent=error.message; $("hero").hidden=false; } finally { clearInterval(timer); $("loading").hidden=true; } });
$("again").onclick=()=>{ $("results").hidden=true; $("hero").hidden=false; $("urlInput").focus(); }; $("download").onclick=()=>{if(!latest)return; const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(latest,null,2)],{type:"application/json"}));a.download="phishing-analysis.json";a.click();URL.revokeObjectURL(a.href);};
